name: "Check project issue"

on:
  workflow_call:

env:
  # project tests and first code review deadlines
  PROJECT_1_TESTS:  "2022-03-01"
  PROJECT_1_REVIEW: "2022-03-08"
  PROJECT_2_TESTS:  "2022-03-29"
  PROJECT_2_REVIEW: "2022-04-05"
  PROJECT_3_TESTS:  "2022-04-19"
  PROJECT_3_REVIEW: "2022-04-26"
  PROJECT_4_TESTS:  "2022-05-10"

  LATE_TESTS_POINTS:  "2" # number of points per deduction (tests)
  LATE_TESTS_DAYS:    "1" # number of days late per deduction (tests)

  LATE_REVIEW_POINTS: "5" # number of points per deduction (first code review)
  LATE_REVIEW_DAYS:   "3" # number of days late per deduction (first code review)

  LATE_MAX_GAP:      "10" # maximum gap in between code reviews
  LATE_MAX_POINTS:   "26" # maximum number of points to deduct

  ASSIGNEES: "['sjengle', 'igentle292', 'mtquach2', 'par5ul1', 'tydaljames', 'ybsolomon']"

jobs:
  check_issue:
    name: "Issue"
    runs-on: ubuntu-latest

    outputs:
      actions: ${{ steps.check_labels.outputs.actions }}
      reviews: ${{ steps.check_labels.outputs.reviews }}
      grade:   ${{ steps.check_labels.outputs.grade }}
      branch:  ${{ steps.check_labels.outputs.branch }}

      name: ${{ steps.check_body.outputs.name }}
      user: ${{ steps.check_body.outputs.user }}

      release: ${{ steps.check_title.outputs.title }}

    steps:
      - name: "Check issue labels"
        id: check_labels
        uses: actions/github-script@v6
        with:
          script: |
            let actions = 'false';
            let reviews = 'false';
            let grade = 'false';
            let branch = 'false';

            const labels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              issue_number: context.issue.number
            });

            if (labels.status != 200) {
              core.setFailed(`Unable to check issue #${context.issue.number} labels. Status: ${labels.status}`);
            }

            if (labels.data.length != 1) {
              core.setFailed(`This workflow is not configured to respond to this issue. Labels: ${labels.data.map(e => e.name).join(", ")}`);
            }
            else if (labels.data[0].name == 'review-request') {

            }
            else if (labels.data[0].name == 'grade-test') {

            }
            else if (labels.data[0].name == 'grade-review') {

            }
            else if (labels.data[0].name == 'grade-release') {

            }
            else {
              core.setFailed(`This workflow is not configured to respond to this issue label: ${labels.data[0].name}`);
            }

            core.setOutput('actions', actions);
            core.setOutput('reviews', reviews);
            core.setOutput('grade', grade);
            core.setOutput('branch', branch);

      - name: "Check issue body"
        id: check_body
        run: |
          echo "Hello world"
          echo "::set-output name=name::Pending"
          echo "::set-output name=user::Pending"

      - name: "Check issue title"
        id: check_title
        run: |
          echo "Hello world"
          echo "::set-output name=release::Pending"


  check_actions:
    name: "Actions"
    runs-on: ubuntu-latest
    needs: [check_issue]
    if: ${{ needs.check_issue.outputs.actions != 'false' }}
    steps:
      - name: "Hello world"
        run: echo "Hello world"

  check_reviews:
    name: "Reviews"
    runs-on: ubuntu-latest
    if: ${{ needs.check_issue.outputs.reviews != 'false' }}
    needs: [check_issue]
    steps:
      - name: "Hello world"
        run: echo "Hello world"

  make_grade:
    name: "Grade"
    runs-on: ubuntu-latest
    if: ${{ needs.check_issue.outputs.grade != 'false' }}
    needs: [check_issue, check_actions, check_reviews]
    steps:
      - name: "Hello world"
        run: echo "Hello world"

  make_branch:
    name: "Branch"
    if: ${{ needs.check_issue.outputs.branch != 'false' }}
    needs: [check_issue, check_actions, check_reviews]
    runs-on: ubuntu-latest
    steps:
      - name: "Hello world"
        run: echo "Hello world"

  check_status:
    name: "Status"
    if: ${{ always() }}
    needs: [check_issue, check_actions, check_reviews, make_grade, make_branch]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':octocat: Hi @${{ github.actor }}! This action is not yet working. Please reach out on Piazza instead.'
            })
