name: "Check project issue"

on:
  workflow_call:
    outputs:
      project_num:
        description: "The project number (e.g. 1, 2, 3a, 3b, or 4)."
        value: ${{ jobs.check_release.outputs.project_num }}
         
      project_ver:
        description: "The project version (e.g. v1.0.0)."
        value: ${{ jobs.check_release.outputs.project_ver }}

jobs:
  check_issue:
    name: "Check Issue"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':octocat: Hi @{{ github.actor }}! This action is not yet working. Please reach out on Piazza instead.'
            })
