name: 'Check project review'

on:
  workflow_call:

env:
  RUN_DETAIL: "\n\n:octocat: @${{ github.actor }} see [run id ${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details."

jobs:
  check_request:
    name: 'Check Request'
    runs-on: 'ubuntu-latest'
    if: ${{ github.event.review.state == 'approved' && github.event.review.user.login == 'sjengle' }}

    steps:
      - name: 'Startup'
        uses: 'actions/github-script@v6'
        with:
          script: |
            github.rest.issues.createComment({owner: context.payload.organization.login, repo: context.payload.repository.name, issue_number: context.payload.pull_request.number, body: `:robot: The GitHub Actions bot is now processing this pull request...${ process.env.RUN_DETAIL}`});
            console.log(context);

  update_request:
    name: 'Update Request'
    runs-on: 'ubuntu-latest'
    needs: ['check_request']

    steps:
      - name: 'Code'
        uses: 'actions/github-script@v6'
        if: ${{ contains(github.event.review.body, 'Resubmit for Code Review' }}
        with:
          script: |
            console.log('Hello');

      - name: 'Quick'
        uses: 'actions/github-script@v6'
        if: ${{ contains(github.event.review.body, 'Resubmit for Quick Review' }}
        with:
          script: |
            console.log('Hello');

      - name: 'Pass'
        uses: 'actions/github-script@v6'
        if: ${{ contains(github.event.review.body, 'Pass' }}
        with:
          script: |
            console.log('Hello');

      - name: 'Update'
        uses: 'actions/github-script@v6'
        if: ${{ !failure() }}
        with:
          script: |
            console.log('Hello');

# TODO Check review
# When a pull request review is submitted, check the status. If the status was
# approved by the instructor, then indicate the request is being processed.
# Otherwise, do nothing.
#
# To process the request, check the review comment. There are three possible
# results:
#
# 1. Resubmit for another normal review -or- quick review. Apply the appropriate
#    labels and respond with instructions for how to request the next appointment.
#    Include what range of dates the next appointment should occur.
#
# 2. Conditional pass or pass. Apply the appropriate labels and respond with
#    instructions for how to prepare the final release. Include when the final
#    release should be created by to avoid late penalties.
#
# 3. Other. This could be associated with a cancelled review for some reason. No
#    labels should be applied.
