# using reusable workflow so do not need to maintain a separate repository and
# worry about keeping all of the node packages updated

name: "Check project issue"

on:
  workflow_call:

env:
  # project tests and first code review deadlines
  PROJECT_1_TESTS:  "2022-03-01"
  PROJECT_1_REVIEW: "2022-03-08"
  PROJECT_2_TESTS:  "2022-03-29"
  PROJECT_2_REVIEW: "2022-04-05"
  PROJECT_3_TESTS:  "2022-04-19"
  PROJECT_3_REVIEW: "2022-04-26"
  PROJECT_4_TESTS:  "2022-05-10"

  LATE_TESTS_POINTS:  "2" # number of points per deduction (tests)
  LATE_TESTS_DAYS:    "1" # number of days late per deduction (tests)

  LATE_REVIEW_POINTS: "5" # number of points per deduction (first code review)
  LATE_REVIEW_DAYS:   "3" # number of days late per deduction (first code review)

  LATE_MAX_GAP:      "10" # maximum gap in between code reviews
  LATE_MAX_POINTS:   "26" # maximum number of points to deduct

  # default messages
  RUN_DETAIL: "@${{ github.actor }} see [run id ${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details."
  FIX_ERRORS: "After addressing the errors, please remove the `error` label and re-open this issue."

jobs:
  check_issue:
    name: "Issue"
    runs-on: ubuntu-latest

    outputs:
      label: ${{ steps.check_labels.outputs.label }}
      name: ${{ steps.check_body.outputs.name }}
      user: ${{ steps.check_body.outputs.user }}
      release: ${{ steps.check_title.outputs.release }}
      project: ${{ steps.check_title.outputs.project }}

    steps:
      - name: "Startup"
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);
            github.rest.issues.createComment({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.payload.issue.number, body: `:robot: The GitHub Actions bot is now processing your request...\n\n:octocat: ${ process.env.RUN_DETAIL` });

      - name: "Check issue labels"
        id: check_labels
        if: ${{ always() }}
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.issue.labels.map(e => e.name);
            console.log(`Labels: ${labels}`);

            if (labels.length == 1) {
              const label = labels[0];

              switch (label) {
                case 'review-request':
                case 'grade-tests':
                case 'grade-review':
                case 'grade-release':
                  core.setOutput('label', label);
                  return;
              }
            }

            // only errors will get this far
            core.setOutput('error_message', `:no_entry: Unable to determine request type from issue #${ context.payload.issue.number } labels: ${labels.length === 0 ? '*(none)*' : labels.join(', ')}\n\nMake sure to use the provided issue templates. ${ process.env.FIX_ERRORS }\n\n:octocat: ${ process.env.RUN_DETAIL }`);
            core.setFailed(`Unable to determine request type from issue #${ context.payload.issue.number } labels: ${labels.length === 0 ? '(none)' : labels.join(', ')}`);

      - name: "Check issue body"
        id: check_body
        if: ${{ always() }}
        uses: actions/github-script@v6
        with:
          script: |
            const body = context.payload.issue.body;
            let error_message = undefined;

            try {
              const pattern = /```json([^`]+)```/;
              const matched = body.match(pattern);

              const parsed = JSON.parse(matched[1]);
              console.log(`Parsed: ${JSON.stringify(parsed)}`);

              if(!parsed.hasOwnProperty('name') || !parsed.hasOwnProperty('username')) {
                error_message = `Both the "name" and "username" properties are required in the issue #${ context.payload.issue.number } body.`;
              }
              else if (parsed.name === "FULL_NAME" || parsed.username === "USF_USERNAME") {
                error_message = `The "name" and "username" properties in the issue #${ context.payload.issue.number } body must be updated.`;
              }
              else {
                core.setOutput('name', parsed.name);
                core.setOutput('user', parsed.username);
                return;
              }
            }
            catch (error) {
              error_message = `Unable to parse issue #${ context.payload.issue.number } body as JSON. Error: ${error.message}`;
            }

            // only errors will get this far
            core.setOutput('error_message', `:no_entry: ${error_message}\n\nMake sure to use the provided issue templates. ${ process.env.FIX_ERRORS }\n\n:octocat: ${ process.env.RUN_DETAIL }`);
            core.setFailed(error_message);

      - name: "Check issue title"
        id: check_title
        if: ${{ always() }}
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.issue.title;
            console.log(`Issue Title: ${title}`);

            const pattern = /^Request.+\b(v([1-4])\.\d+\.\d+)$/;
            const matched = title.match(pattern);

            if (matched !== null && matched.length === 3) {
              const release = matched[1];
              const project = matched[2];
              core.setOutput('release', release);
              core.setOutput('project', project);
              console.log(`Release: ${release}, Project: ${project}`);
            }
            else {
              core.setOutput('error_message', `:no_entry: Unable to parse release from issue #${ context.payload.issue.number } title:\n\n> ${title}\n\nMake sure to replace \`v0.0.0\` in the issue title with a properly-formated release number. ${ process.env.FIX_ERRORS }\n\n:octocat: ${ process.env.RUN_DETAIL }`);
              core.setFailed(`Unable to parse release from issue #${ context.payload.issue.number } title: ${title}`);
            }

      - name: "Check failures"
        id: check_failures
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            const steps = ${{ toJSON(steps) }};
            console.log(steps);

            for (const step in steps) {
              if (steps[step].outcome == "failure" && steps[step].outputs.hasOwnProperty('error_message')) {
                // output the error as an issue comment
                github.rest.issues.createComment({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.payload.issue.number, body: steps[step].outputs.error_message});
              }
            }

            // close the issue, assign it to the user, and apply the 'error' label
            const labels = context.payload.issue.labels.map(e => e.name);
            labels.push('error');

            github.rest.issues.update({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.payload.issue.number, state: 'closed', assignees: [context.actor], labels: labels});

  check_actions:
    name: "Actions"
    runs-on: ubuntu-latest
    needs: [check_issue]
    if: ${{ needs.check_issue.outputs.label == 'grade-release' || needs.check_issue.outputs.label == 'grade-tests' || needs.check_issue.outputs.label == 'review-request' }}

    outputs:
      error_message: ${{ steps.check_status.outputs.error_message }}
      submitted_id: ${{ steps.find_passing.outputs.submitted_id }}
      submitted_date: ${{ steps.find_passing.outputs.submitted_date }}

    steps:
      - name: "Find completed action runs"
        uses: actions/github-script@v6
        id: find_complete
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'project-release.yml',
              per_page: 100
            });

            if (runs.status != 200) {
              const error_message = `Unable to fetch runs for "Check project release" action (status ${runs.status}).`;
              core.exportVariable('ERROR_MESSAGE', `:no_entry: ${error_message}\n\nThis may be related to an outage. Check [GitHub status](https://www.githubstatus.com/) before trying again. ${ process.env.FIX_ERRORS }\n\n:octocat: ${ process.env.RUN_DETAIL }`);
              core.setFailed(error_message);
            }
            else {
              console.log(`Found ${runs.data.total_count} workflow runs total.`);
              const filtered = runs.data.workflow_runs.filter(run => run.status === 'completed');

              if (filtered.length < 1) {
                core.exportVariable('ERROR_MESSAGE', `:no_entry: Unable to find any completed workflow runs.\n\nMake sure to create a release and wait for its action run to complete. ${ process.env.FIX_ERRORS }\n\n:octocat: ${ process.env.RUN_DETAIL }`);
                core.setFailed(`Unable to find any completed workflow runs.`);
              }
              else {
                console.log(`Found ${filtered.length} completed runs: ${filtered.map(run => run.head_branch).join(', ')}`);
                return filtered;
              }
            }

      - name: "Find release runs"
        uses: actions/github-script@v6
        id: find_release
        env:
          RELEASE: ${{ needs.check_issue.outputs.release }}
        with:
          script: |
            const release = process.env.RELEASE;
            console.log(`Release: ${release}`);

            const runs = ${{ steps.find_complete.outputs.result }};
            const filtered = runs.filter(run => run.head_branch === release);

            if (filtered.length < 1) {
              core.exportVariable('ERROR_MESSAGE', `:no_entry: Unable to find any completed workflow runs for release: \`${release}\`\n\nMake sure the release in the issue title is associated with a completed (*not* in progress, waiting, or cancelled) action run. ${ process.env.FIX_ERRORS }\n\n:octocat: ${ process.env.RUN_DETAIL }`);
              core.setFailed(`Unable to find any completed workflow runs for release ${release}.`);
            }
            else {
              console.log(`Found ${filtered.length} runs for ${release}:`);
              console.log(filtered);
              return filtered;
            }

      - name: "Find passing runs"
        uses: actions/github-script@v6
        id: find_passing
        env:
          RELEASE: ${{ needs.check_issue.outputs.release }}
          LABEL: ${{ needs.check_issue.outputs.label }}
        with:
          script: |
            const release = process.env.RELEASE;
            const label = process.env.LABEL;
            console.log(`Label: ${label}, Release: ${release}`);

            const runs = ${{ steps.find_release.outputs.result }};

            // try to find a successful run
            const success = runs.find(run => run.conclusion === 'success');

            if (success != undefined) {
              console.log(`Found successful run:`);
              console.log(success);
              core.setOutput(submitted_id, success.id);
              core.setOutput(submitted_date, success.head_commit.timestamp);
              console.log(`ID: ${success.id}, Submitted: ${success.head_commit.timestamp}`);
              return;
            }
            else if ('${{ needs.check_issue.outputs.label }}' == 'grade-tests') {
              for (const run of runs) {
                const results = await github.rest.actions.listJobsForWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id,
                  filter: 'latest',
                  per_page: 100
                });

                if (results.status != 200) {
                  const error_message = `Unable to fetch jobs for action run ${run.id}.`;
                  core.exportVariable('ERROR_MESSAGE', `:no_entry: ${error_message}\n\nThis may be related to an outage. Check [GitHub status](https://www.githubstatus.com/) before trying again. ${ process.env.FIX_ERRORS }\n\n:octocat: ${ process.env.RUN_DETAIL }`);
                  core.setFailed(error_message);
                }
                else {
                  const test_job = results.data.jobs.find(job => job.name == 'Check / JUnit Tests');
                  console.log(`Check / JUnit Tests:`);
                  console.log(test_job);

                  if (test_job.conclusion == 'success') {
                    core.setOutput('submitted_id', run.id);
                    core.setOutput('submitted_date', run.head_commit.timestamp);
                    console.log(`ID: ${run.id}, Submitted: ${run.head_commit.timestamp}`);
                    return;
                  }
                }
              }

              // only get here if no successful test run found
              core.exportVariable('ERROR_MESSAGE', `:no_entry: No runs found that passed all tests for release \`${release}\`.\n\nMake sure the release in the issue title is associated with a completed run that passes all of the tests (the other checks are *optional* for this grade). ${ process.env.FIX_ERRORS }\n\n:octocat: ${ process.env.RUN_DETAIL }`);
              core.setFailed(`No runs found that passed all tests for release ${release}.`);
            }
            else {
              core.exportVariable('ERROR_MESSAGE', ':no_entry: No runs found that passed all tests and checks for release \`${release}\`.\n\n\n\nMake sure there is a **completed** and **successful** run that passes all of the required tests and checks. ${ process.env.FIX_ERRORS }\n\n:octocat: ${ process.env.RUN_DETAIL }');
              core.setFailed(`No runs found that passed all tests and checks for release ${release}.`);
            }

      - name: "Check status"
        id: check_status
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            console.log(process.env.ERROR_MESSAGE);
            core.setOutput('error_message', process.env.ERROR_MESSAGE);

  check_reviews:
    name: "Reviews"
    runs-on: ubuntu-latest
    if: ${{ needs.check_issue.outputs.label == 'grade-release' || needs.check_issue.outputs.label == 'review-request' }}
    needs: [check_issue]
    steps:
      - name: "Hello world"
        run: echo "Hello world"

  make_grade:
    name: "Grade"
    runs-on: ubuntu-latest
    if: ${{ !failure() && (needs.check_issue.outputs.label == 'grade-release' || needs.check_issue.outputs.label == 'grade-tests' || needs.check_issue.outputs.label == 'grade-review') }}
    needs: [check_issue, check_actions, check_reviews]

    outputs:
      error_message: ${{ steps.check_status.outputs.error_message }}

    steps:
      - name: "Lookup deadline"
        id: find_deadline
        uses: actions/github-script@v6
        with:
          script: |
              const config = {
                label: '${{ needs.check_issue.outputs.label }}',
                release: '${{ needs.check_issue.outputs.release }}',
                project: '${{ needs.check_issue.outputs.project }}'
              };

              // set submitted date
              switch (config.label) {
                // for tests and final release, based on release
                case 'grade-release':
                case 'grade-tests':
                  config.submitted_id = '${{ needs.check_actions.outputs.submitted_id }}';
                  config.submitted_date = '${{ needs.check_actions.outputs.submitted_date }}';
                  config.submitted_type = 'action run';
                  break;

                // for code review, based on pull request approval
                case 'grade-review':
                  config.submitted_type = 'pull request';
                  core.warning('Not yet implemented.');
                  break;

                default:
                  core.setFailed(`Unexpected label: ${config.label}`);
              }

              // set deadline date
              switch (config.label) {
                // based on test deadline
                case 'grade-tests':
                  config.deadline = process.env[`PROJECT_${config.project}_TESTS`];
                  config.late_points = process.env.LATE_TESTS_POINTS;
                  config.late_days = process.env.LATE_TESTS_DAYS;
                  break;

                // based on review deadline -or- last code review
                case 'grade-review':
                  core.warning('Not yet implemented.');
                  break;

                // based on last code review
                case 'grade-release':
                  core.warning('Not yet implemented.');
                  break;

                default:
                  core.setFailed(`Unexpected label: ${config.label}`);
              }

              console.log(config);
              return config;

      - name: "Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: "Install luxon"
        run: npm install luxon

      - name: "Calculate grade"
        id: calc_grade
        uses: actions/github-script@v6
        with:
          script: |
            const { DateTime } = require('luxon');
            const zone = 'America/Los_Angeles';

            const config = ${{ steps.find_deadline.outputs.result }};
            console.log(config);

            config.submitted_date = DateTime.fromISO(config.submitted_date, {zone: zone});
            config.deadline = DateTime.fromISO(config.deadline, {zone: zone});

            console.log(`Submitted: ${config.submitted_date.toString()}, Deadline: ${config.deadline.toString()}`);
            console.log('hello');

  make_branch:
    name: "Branch"
    if: ${{ !failure() && needs.check_issue.outputs.label == 'request-review' }}
    needs: [check_issue, check_actions, check_reviews]
    runs-on: ubuntu-latest
    steps:
      - name: "Hello world"
        run: echo "Hello world"

  check_status:
    name: "Status"
    if: ${{ always() }}
    needs: [check_actions, check_reviews, make_grade, make_branch]
    runs-on: ubuntu-latest
    steps:
      - name: "Check status"
        uses: actions/github-script@v6
        with:
          script: |
            const results = ${{ toJSON(needs) }}
            console.log(results);

            for (const id in results) {
              if (results[id].result == "failure" && results[id].outputs.hasOwnProperty('error_message')) {
                // output the error as an issue comment
                github.rest.issues.createComment({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.payload.issue.number, body: results[id].outputs.error_message});
              }
            }

            // close the issue, assign it to the user, and apply the 'error' label
            const labels = context.payload.issue.labels.map(e => e.name);
            labels.push('error');

            github.rest.issues.update({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.payload.issue.number, state: 'closed', assignees: [context.actor], labels: labels});
